apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-blue
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
      version: blue
  template:
    metadata:
      labels:
        app: demo
        version: blue
    spec:
      containers:
      - name: demo
        image: nginx:latest   # placeholder
        ports:
        - containerPort: 8080
